name: Crust Pinner Template
on:
  # mannual trigger
  #workflow_dispatch:
  push:
    branches: 
      - main

jobs:
  pin_on_crust:
    name: Pin template website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Upload to crustwebsites
        uses: crustio/ipfs-upload-action@v2.0.2
        id: uploadsite
        with:
          path: './.github/template'
          seeds: ${{ secrets.CRUST_SEEDS }}

      - name: Echo Hash Value
        run: echo "Hash value is: ${{ steps.uploadsite.outputs.hash }}"
  #      run: echo "{foo}={bar}" >> $GITHUB_OUTPUT
      # - name: Pin to Crust
      #   id: pintocrust
      #   uses: crustio/ipfs-crust-action@v1.0.8
      #   with:
      #     cid: ${{ steps.uploadsite.outputs.hash }}
      #     seeds: ${{ secrets.CRUST_SEEDS }}
